name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' #for all branches
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build
      
    - name: 📦 Create deployment artifact
      run: |
        zip -r deploy.zip . -x ".*" -x "deploy.zip" -x "node_modules/*"
    
    - name: 💾 Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploy-artifact
        path: deploy.zip
        
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Download artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy-artifact
        
    - name: 📂 Extract artifact
      run: unzip deploy.zip
